import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {dirname,extname,join} from 'node:path';
import {tmpdir} from 'node:os';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url)),runFile=promisify(execFile);
function parseResult(stdout,stderr,converter){if(!stdout.trim())throw new Error('表格中没有可导入的数据。');const mismatch=stderr.match(/EXPECTED_COUNT=(\d+);ACTUAL_COUNT=(\d+)/);return {spectrumText:stdout.trim(),warnings:mismatch?[`表格元数据声明 ${mismatch[1]} 个通道，但只读取到 ${mismatch[2]} 行数值数据；未自动补值，请核对原文件。`]:[],converter}}
export async function importSpreadsheet(bytes,filename){const ext=extname(filename).toLowerCase();if(!['.xls','.xlsx'].includes(ext))throw new Error('仅支持 .xls 或 .xlsx。');if(!Buffer.isBuffer(bytes)||!bytes.length||bytes.length>20_000_000)throw new Error('表格文件必须为 1–20 MB 的有效字节。');const dir=await mkdtemp(join(tmpdir(),'nexus-naa-')),input=join(dir,`input${ext}`);try{await writeFile(input,bytes);let comError=null;if(process.platform==='win32'){try{const out=await runFile('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',join(root,'scripts','excel-to-spectrum.ps1'),'-Path',input],{windowsHide:true,timeout:60000,maxBuffer:20_000_000});return parseResult(out.stdout,out.stderr,'excel-com-readonly')}catch(e){comError=e}}const bundledPython=join(dirname(process.execPath),'..','..','python',process.platform==='win32'?'python.exe':'bin/python3'),python=process.env.NAA_PYTHON||bundledPython;try{const out=await runFile(python,[join(root,'scripts','spreadsheet-to-spectrum.py'),input],{windowsHide:true,timeout:60000,maxBuffer:20_000_000}),result=parseResult(out.stdout,out.stderr,'python-readonly-fallback');if(comError)result.warnings.unshift('Excel 桌面组件不可用，已自动改用只读解析器。');return result}catch(e){throw new Error(`表格导入失败：${String(e.stderr||e.message||e).trim()}${comError?'；Excel 桌面组件也不可用。':''}`)}}finally{await rm(dir,{recursive:true,force:true})}}

export async function normalizeSpectrumFile({filename,fileBase64,fileText}){const ext=extname(String(filename||'')).toLowerCase();if(['.xls','.xlsx'].includes(ext)){if(typeof fileBase64!=='string'||!fileBase64||!/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(fileBase64))throw new Error('Excel 文件需要有效的 fileBase64。');return importSpreadsheet(Buffer.from(fileBase64,'base64'),filename)}if(!['.csv','.txt','.dat','.spe'].includes(ext))throw new Error('支持 CSV、TXT、DAT、SPE、XLS 和 XLSX。');if(typeof fileText!=='string'||!fileText.trim())throw new Error('文本谱需要 fileText。');if(Buffer.byteLength(fileText)>10_000_000)throw new Error('文本谱超过 10 MB 限制。');return {spectrumText:fileText,warnings:[],converter:'text'}}
