import test from "node:test"; import assert from "node:assert/strict"; import { readFile } from "node:fs/promises";
import { queryGammaLines } from "../src/core.js";
const db=JSON.parse(await readFile(new URL("../data/nuclear-lines.json",import.meta.url),"utf8"));
test("nuclear database has resolvable provenance",()=>{assert.match(db.datasetId,/2026-09-06/);assert.equal(db.lines.length,81);assert.equal(new Set(db.lines.map(x=>x.id)).size,81);for(const line of db.lines){assert.ok(line.sourcePage>0);assert.ok(line.energyKeV>0);assert.ok(db.sources[line.sourceId]?.url)}});
test("Cs-137 reference line is retrievable",()=>{const hits=queryGammaLines(db,661.657,0.01);assert.equal(hits[0].nuclide,"Cs-137");assert.equal(hits[0].absDeltaKeV,0)});
test("Na-24 companion lines coexist in snapshot",()=>{const lines=db.lines.filter(x=>x.nuclide==="Na-24");assert.deepEqual(lines.map(x=>x.energyKeV),[1368.626,2754.007])});
test("expanded calibration sources retain their reviewed line sets",()=>{assert.equal(db.lines.filter(x=>x.nuclide==='Eu-152').length,14);assert.equal(db.lines.filter(x=>x.nuclide==='Eu-154').length,12);assert.deepEqual(db.lines.filter(x=>x.nuclide==='Am-241').map(x=>x.energyKeV),[26.3446,33.1963,59.5409,98.95])});
test("supplied workbook records are independently reviewed and preserve provenance",()=>{const supplied=db.lines.filter(x=>x.sourceId==='COMPETITION_LIBRARY_2026');assert.equal(supplied.length,23);assert.ok(supplied.every(x=>x.verification==='independently_reviewed'&&x.auditSourceUrl));assert.equal(db.sources.COMPETITION_LIBRARY_2026.qualification,'supplied_reference_independently_reviewed');assert.deepEqual(db.lines.filter(x=>x.nuclide==='Ba-133').map(x=>x.energyKeV),[276.3989,302.8508,356.0129,383.8485]);assert.equal(db.lines.filter(x=>x.nuclide==='Bi-214').length,3)});
test("Th-234 photons are not mislabeled as direct U-238 emissions",()=>{const lines=db.lines.filter(x=>x.id==='COMP2026-01'||x.id==='COMP2026-02');assert.deepEqual(lines.map(x=>x.nuclide),['Th-234','Th-234']);assert.ok(lines.every(x=>x.proxyFor==='U-238'&&/equilibrium/i.test(x.proxyCondition)));assert.equal(lines[1].intensityPercent,2.18)});
